@extends('layouts.admindashboard')

@section('content')
<div class="content">
    <div class="container-xl">
        <div class="row row-cards">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Dashboard Home</h3>
                    </div>
                    <div class="card-body">
                        <div class="alert alert-success">
                            Hi there! Thank you for using the <code><a href="https://github.com/Proxeuse/fortify-tabler">Proxeuse/fortify-tabler</a></code> FortifyUI preset.
                            We've automatically installed the authentication pages (login, registration, etc.) and the
                            profile edit page. You're now able to edit anything of your likings.
                            This version of Proxeuse/fortify-tabler also features automatic avatars and manual avatar
                            uploads. The default avatar image is generated by the <a href="https://api.proxeuse.com/avatars/" target="_blank">Proxeuse Avatar API</a>,
                            you are free to change this to any other generator.
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Quick Access Cards -->
            <div class="col-md-6 col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex align-items-center">
                            <div class="subheader">LDAP Users & Roles</div>
                        </div>
                        <div class="h1 mb-3 text-primary">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
                                <path d="M12 10m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
                                <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"></path>
                            </svg>
                        </div>
                        <div class="d-flex mb-2">
                            <div>Manage LDAP users and their roles</div>
                        </div>
                        <div class="mt-3">
                            <a href="{{ route('admin.viewrole.index') }}" class="btn btn-primary">
                                View Users & Roles
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
